#############################################################################
# Makefile for building: roi_draw
# Generated by qmake (3.1) (Qt 5.15.17)
# Project:  roi_draw.pro
# Template: app
# Command: /home/khoatn9/working/thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -o Makefile roi_draw.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /home/khoatn9/working/thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/khoatn9/working/thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/khoatn9/working/thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = midl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: roi_draw.pro ../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf ../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/qdevice.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/device_config.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/angle.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/windows-vulkan.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/g++-win32.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/windows-desktop.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/qconfig.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/default_post.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qt.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/gc_binaries.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/resources_functions.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/resources.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/moc.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/windows.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/yacc.prf \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/lex.prf \
		roi_draw.pro \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/mediaservice/dsengine.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/mediaservice/qtmedia_audioengine.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/audio/qtaudio_windows.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/playlistformats/qtmultimedia_m3u.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qgif.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qico.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qjpeg.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_debugger.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_inspector.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_local.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_messages.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_native.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_nativedebugger.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_preview.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_profiler.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_quickprofiler.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_server.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_tcp.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/bearer/qgenericbearer.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/styles/qwindowsvistastyle.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Quick.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Multimedia.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Gui.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5QmlModels.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Qml.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Network.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Core.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick.2/qtquick2plugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/qtquickcontrols2plugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Layouts/qquicklayoutsplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtMultimedia/declarative_multimedia.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Window.2/windowplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQml/qmlplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Templates.2/qtquicktemplates2plugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQml/Models.2/modelsplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQml/WorkerScript.2/workerscriptplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Universal/qtquickcontrols2universalstyleplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Imagine/qtquickcontrols2imaginestyleplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Fusion/qtquickcontrols2fusionstyleplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Material/qqc2materialstyleplugin.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/qtmain.prl \
		../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/build_pass.prf \
		qml.qrc
	$(QMAKE) -o Makefile roi_draw.pro
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/qdevice.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/device_config.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/angle.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/windows-vulkan.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/g++-win32.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/common/windows-desktop.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/qconfig.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/default_post.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qt.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/gc_binaries.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/resources_functions.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/resources.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/moc.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/win32/windows.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/yacc.prf:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/lex.prf:
roi_draw.pro:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/mediaservice/dsengine.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/mediaservice/qtmedia_audioengine.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/audio/qtaudio_windows.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/playlistformats/qtmultimedia_m3u.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qgif.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qico.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qjpeg.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_debugger.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_inspector.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_local.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_messages.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_native.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_nativedebugger.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_preview.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_profiler.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_quickprofiler.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_server.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_tcp.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/bearer/qgenericbearer.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/styles/qwindowsvistastyle.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Quick.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Multimedia.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Gui.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5QmlModels.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Qml.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Network.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/Qt5Core.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick.2/qtquick2plugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/qtquickcontrols2plugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Layouts/qquicklayoutsplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtMultimedia/declarative_multimedia.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Window.2/windowplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQml/qmlplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Templates.2/qtquicktemplates2plugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQml/Models.2/modelsplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQml/WorkerScript.2/workerscriptplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Universal/qtquickcontrols2universalstyleplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Imagine/qtquickcontrols2imaginestyleplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Fusion/qtquickcontrols2fusionstyleplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Material/qqc2materialstyleplugin.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/qtmain.prl:
../../thirdparty/mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/features/build_pass.prf:
qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile roi_draw.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) /home/khoatn9/working/projects/roi_draw/roi_draw_plugin_import.cpp /home/khoatn9/working/projects/roi_draw/roi_draw_qml_plugin_import.cpp .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
